### ISSUE TITLE
import easydl error

### ISSUE THREAD

**Issue by zhangzp9970** [thuml/easydl#1]
当我尝试使用`from easydl import *`导入easydl 库的时候，报错：
[easydl] tensorflow not available!
但是我安装了tensorflow
pip list 的输出如下：
tensorflow            2.0.0
tensorflow-estimator  2.0.1
easydl                2.0.7

**Comment by zhangzp9970** [comment]
solved

**Comment by wenzihan** [comment]
请问是怎么解决的呀？我也遇到了这个问题，谢谢~

**Comment by zhangzp9970** [comment]
好像是easydl不支持tensorflow2,所以会输出这个error，但是库已经被正常导入了，可以忽略这个使用。
